databases:
  - name: ecocycle2
    plan: free
    databaseName: ecocycle2
    user: seba

services:
  - type: web
    plan: free
    name: ecocycle
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ecocycle.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecocycle2
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4